
package fr.eni.mvnbook.banque.ws.client.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWebservice", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWebservice {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws BanqueException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "virement", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.Virement")
    @ResponseWrapper(localName = "virementResponse", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.VirementResponse")
    public void virement(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns fr.eni.mvnbook.banque.ws.client.proxy.Client
     * @throws BanqueException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.AuthResponse")
    public Client auth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws BanqueException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fr.eni.mvnbook.banque.ws.client.proxy.Compte>
     * @throws BanqueException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comptes", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.Comptes")
    @ResponseWrapper(localName = "comptesResponse", targetNamespace = "http://www.eni.fr/ws/mvnbook/banque-webservice", className = "fr.eni.mvnbook.banque.ws.client.proxy.ComptesResponse")
    public List<Compte> comptes(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0)
        throws BanqueException_Exception
    ;

}
